In [1]:
pwd

'G:\\SuperDataScience\\Machine Learning A-Z\\Part 2 - Regression\\Section 4 - Simple Linear Regression\\Simple_Linear_Regression'

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Salary_Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 1].values

In [4]:
from sklearn.cross_validation import train_test_split

C:\Users\Rajath\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
regressor = LinearRegression(n_jobs=15)

In [19]:
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=15, normalize=False)

In [20]:
y_pred = regressor.predict(X_test)

In [21]:
y_pred

array([ 40748.96184072, 122699.62295594,  64961.65717022,  63099.14214487,
       115249.56285456, 107799.50275317])

In [22]:
def compare(yact,ypr):
    return yact-ypr

In [24]:
compare(y_test,y_pred)

array([-3017.96184072,  -308.62295594, -7880.65717022,   118.85785513,
        1719.43714544,  1631.49724683])

In [25]:
y_test

array([ 37731., 122391.,  57081.,  63218., 116969., 109431.])

In [26]:
y_test[0]

37731.0

In [ ]:
40747-